name: 'Factorio Mod Portal API Publish'
author: 'Penguin_Spy'
description: 'Publishes a Factorio mod to the mod portal using an API token'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'settings'  
  color: 'purple'
